export default {
  USER_REPOSITORY: 'USER_REPOSITORY',
  ORDER_REPOSITORY: 'ORDER_REPOSITORY',
  NOTIFICATION_REPOSITORY: 'NOTIFICATION_REPOSITORY',
  ADDRESSES_REPOSITORY: 'ADDRESSES_REPOSITORY',
};
