export default {
  USER_REPOSITORIES: 'USER_REPOSITORIES',
  ORDER_REPOSITORIES: 'ORDER_REPOSITORIES',
  NOTIFICATION_REPOSITORY: 'NOTIFICATION_REPOSITORY',
  ADDRESSES_REPOSITORY: 'ADDRESSES_REPOSITORY',
};
